# Generated by Django 5.2.6 on 2025-10-17 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SwapAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('par_coupons', 'Par Coupons Analysis'), ('indexed_coupons', 'Indexed Coupons Analysis'), ('comparison', 'Comparison Analysis')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notional', models.FloatField(help_text='Notional amount')),
                ('swap_length', models.FloatField(help_text='Swap length in years')),
                ('evaluation_date', models.DateField(help_text='Evaluation date')),
                ('coupon_data', models.JSONField(help_text='Detailed coupon calculations')),
                ('par_coupon_amounts', models.JSONField(help_text='Par coupon amounts')),
                ('indexed_coupon_amounts', models.JSONField(help_text='Indexed coupon amounts')),
                ('difference_analysis', models.JSONField(help_text='Difference analysis between methods')),
                ('total_par_amount', models.FloatField(help_text='Total par coupon amount')),
                ('total_indexed_amount', models.FloatField(help_text='Total indexed coupon amount')),
                ('difference_amount', models.FloatField(help_text='Difference between methods')),
                ('max_rate_difference', models.FloatField(help_text='Maximum rate difference')),
            ],
            options={
                'verbose_name': 'Swap Analysis Result',
                'verbose_name_plural': 'Swap Analysis Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
