# Generated by Django 5.2.6 on 2025-10-17 23:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('HullWhite', 'Hull-White 1-Factor'), ('BlackKarasinski', 'Black-Karasinski'), ('G2', 'G2++ 2-Factor')], max_length=20)),
                ('calibration_type', models.CharField(choices=[('standard', 'Standard Calibration'), ('constrained', 'Constrained Calibration'), ('normal_vol', 'Normal Volatility Calibration')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('parameters', models.JSONField(help_text='Calibrated model parameters')),
                ('param_string', models.TextField(help_text='Human-readable parameter string')),
                ('rmse_price_error', models.FloatField(help_text='Root mean square error for prices')),
                ('rmse_vol_error', models.FloatField(help_text='Root mean square error for volatilities')),
                ('market_data', models.JSONField(help_text='Market data used for calibration')),
                ('calibration_report', models.JSONField(help_text='Detailed calibration report data')),
            ],
            options={
                'verbose_name': 'Calibration Result',
                'verbose_name_plural': 'Calibration Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
